name: .NET

on:
  push:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: git init
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
